### ISSUE TITLE
tif or jpg format of the HE image data

### ISSUE THREAD

**Issue by JunMa11** [Swarbricklab-code/BrCa_cell_atlas#10]
Dear all,

Thanks for sharing the awesome work.

https://zenodo.org/record/4739739#.Yhpmm-jMJPY

Could you please share the original HE images in **jpg** or **tif** format?
Just like the 10X SRT data
https://www.10xgenomics.com/resources/datasets/human-breast-cancer-ductal-carcinoma-in-situ-invasive-carcinoma-ffpe-1-standard-1-3-0

**Comment by johnyaku** [comment]
Hi Jun.

The Zenodo repo above contains HE images in two formats.
1. `images.pdf` provides all images in a single document (together with annotations) for convenient viewing
2. `spatial.tar.gz` contains the raw **jpg** images in hi and lo resolution formats
