### ISSUE TITLE
Single Cell Count

### ISSUE THREAD

**Issue by Ethan-Earlie** [Swarbricklab-code/BrCa_cell_atlas#14]
Hello, I have a question about the number of cells present in the published analyses. In the Figure 1.A legend there are ~130k cells quoted for the UMAP. However, in the published data on the Broad Single Cell Portal there seem to be ~100k cells. Would you please be able to help clarify this discrepancy and how many cells were used to generate the main Fig.1.A UMAP.

Thank you!

**Comment by johnyaku** [comment]
Basically, I believe that this was a result of filtering.  I'll let the authors point you to the filtering conditions that led to this reduction, but in the meantime I have placed the raw unfiltered counts on the Broad's Single Cell Portal: https://singlecell.broadinstitute.org/single_cell/study/SCP1039/a-single-cell-and-spatially-resolved-atlas-of-human-breast-cancers#study-download
The file in question is `brca_mini_atlas_raw_unfiltered.zip`

**Comment by Ethan-Earlie** [comment]
I see, thank you for your quick reply!
