### ISSUE TITLE
About the "filtered_count_matrices.tar.gz" download on zenodo 

### ISSUE THREAD

**Issue by lhyNB** [Swarbricklab-code/BrCa_cell_atlas#19]
Hi, i am willing to know why there is an error like "the compressed file format is unknown or the contents are corrupted" when i unzip the file. When i unzip the other files download from the Zenodo, everything went well, however.  Is there a problem with the uploaded file and could you please send me the latest file "filtered_count_matrices.tar.gz"  that can be unzipped？Here is my email  address 22119069@zju.edu.cn.  Thank u. Wish u have a good day.

**Comment by johnyaku** [comment]
I just downloaded and tested the file.
Extracted OK for me with `tar -xvzf filtered_count_matrices.tar.gz`.
Perhaps the file was corrupted during transfer?
You can check the md5 checksum by running `md5sum filtered_count_matrices.tar.gz` on the downloaded file.
The result should match the md5 checksum displayed under the filename on Zenodo.

Once you manage to extract the tarball, you will find folders for each sample.
Note that the actual matrices inside the archive (such as `filtered_count_matrices/1142243F_filtered_count_matrix/matrix.mtx.gz`) are not actually gzipped files, despite the `.gz` extension. You can either compress them or use them as is, depending on your downstream application.

In case you need to load these count matrices into Seurat, please check the following discussion: https://github.com/Swarbricklab-code/BrCa_cell_atlas/issues/3

**Comment by lhyNB** [comment]
I see…I tried again and it works. Thanks
