### ISSUE TITLE
Potentially application of ecotyper?

### ISSUE THREAD

**Issue by WangKang-Leo** [Swarbricklab-code/BrCa_cell_atlas#22]
Thanks for your great work! I am just wondering whether I can apply ecotyper (https://github.com/digitalcytometry/ecotyper) on our bulk RNA-seq, and treat your well annotated single-cell dataset as discovery. Thanks!

**Comment by johnyaku** [comment]
Thanks for your interest. 

This question is probably best directed to the `ecotyper` developers.
