### ISSUE TITLE
Request for gene_clusters.txt file for AUCell analysis for spatial data

### ISSUE THREAD

**Issue by tahseen-igib** [Swarbricklab-code/BrCa_cell_atlas#23]
Hi

Thanks for providing the codes for your interesting paper
However I am stuck at AUcell analysis for spatial data where i am not able to find file used for temp_metagenes.
**temp_metagenes <- read.delim("/share/ScratchGeneral/sunwu/projects/MINI_ATLAS_PROJECT/Sept2019/11_visium_brca_metagenes/gene_clusters.txt")**

**https://github.com/Swarbricklab-code/BrCa_cell_atlas/blob/main/spatial_analysis/brca_gene_module_spatial_AUCell.R**

It would be really a great help if you can provide the file.

Thanks!

**Comment by johnyaku** [comment]
Hi @tahseen-igib.

I've uploaded `gene_clusters.txt` to the `spatial_analysis/` directory of this repo, and adjusted the path in `brca_gene_module_spatial_AUCell.R`.

There are a number of other hard-coded paths that you may need to adapt for your platform. Most of the data files that these reference can be generated by other scripts in the repo, but if you come across other missing data then please let us know.
