### ISSUE TITLE
Question about difference between AUcell & other geneset enrichment tools

### ISSUE THREAD

**Issue by tahseen-igib** [Swarbricklab-code/BrCa_cell_atlas#24]
Hi

Thanks for prompt response for my previous question.
How AUcell is different from GSEA or other gene set enrichment tools. Can u pls elaborate.

Thanks
Tahseen

**Comment by johnyaku** [comment]
That question is probably best directed to the [AUCell developers](https://github.com/aertslab/AUCell/issues)
