### ISSUE TITLE
How was GSE176078_Wu_etal_2021_BRCA_scRNASeq.tar.gz created?

### ISSUE THREAD

**Issue by RegnerM2015** [Swarbricklab-code/BrCa_cell_atlas#8]
Hi @sunnyzwu,

Very impressive paper and Git repo! 

I am looking at your GEO repository at https://www-ncbi-nlm-nih-gov.libproxy.lib.unc.edu/geo/query/acc.cgi?acc=GSE176078.

I have downloaded and uncompressed GSE176078_Wu_etal_2021_BRCA_scRNASeq.tar.gz to reveal the standard output of cellranger (mtx, features.tsv and barcodes.tsv). 

How was this multi-sample dataset created exactly? Specifically, I would like to know which of the following methods were used to make the files in GSE176078_Wu_etal_2021_BRCA_scRNASeq.tar.gz:

1. Ran cellranger aggr to combine all samples into one cellranger count output
2. Decomposed a CCA-integrated Seurat object into mtx, features, and barcodes files
3. Decomposed a non-integrated Seurat object (using Seurat's merge()) into mtx, features, and barcodes files

Please let me know which method (1,2, or 3) most closely aligns with how this file was constructed or if a different approach was used to make the files in GSE176078_Wu_etal_2021_BRCA_scRNASeq.tar.gz. 

Thanks in advance!

**Comment by yewero** [comment]
@RegnerM2015 The gene expression matrix in `GSE176078_Wu_etal_2021_BRCA_scRNASeq.tar.gz` is a raw count matrix. Also, it is the same with the matrix generated by merging (`cbind`) all the matrices in each sample in `GSE176078_RAW.tar`. Thus, the multi-sample matrix could be generated by the first method you listed.

**Comment by RegnerM2015** [comment]
Hi @yewero,

Thank you for your help! You answered my question.
