### ISSUE TITLE
The result files of Stereoscope are missing

### ISSUE THREAD

**Issue by yewero** [Swarbricklab-code/BrCa_cell_atlas#9]
Specifically, there are 3 related files:
https://github.com/Swarbricklab-code/BrCa_cell_atlas/blob/adfbc29d4dc628336c2c2593cdc638b8c0a7d370/spatial_analysis/append_stereoscope_data.R#L40-L50
How could I find these files?

**Comment by johnyaku** [comment]
I've added the Stereoscope results to `spatial_analysis/stsc`.
I've fixed some of the paths in `append_stereoscope_data.R` but some are still specific to our HPC cluster. 
You might have to adjust some more paths to get the script to run (and please open a pull request if you do!) but at least you can explore the data. 
Sorry about the hold up.
